#!/bin/sh

/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

devmnt=$(mount | grep -c devtmpfs)
if [ "${devmnt}" -eq 0 ]; then
    /bin/mount -t devtmpfs devtmpfs /dev
fi

if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

export TERM=dumb
export HOME=/root

while true; do
    cat /etc/issue

    sh
done
